### PR TITLE
Adding scala support.

### PR DESCRIPTION
**Pull request by iammichiel**
Adding scala syntax :

```
// TODO: $0
/* TODO: $0 */
```

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Is there a reason to enable both `//` and `/*` style `TODO` comments in scala? Would just `//` not work?

**Comment by iammichiel** [comment]
As both comment syntaxes are supported in scala, why not activate it in both cases? `//` will probably be the most used.

**Comment by kevinsawicki** [comment]
> As both comment syntaxes are supported in scala, why not activate it in both cases? 

It seems a little confusing to have 2 todo snippets listed in autocomplete for scala files.

Are you okay with just going with the `//` case to start?

**Comment by iammichiel** [comment]
Yes, good for me. I'll update my commit.

**Comment by kevinsawicki** [comment]
Awesome, thanks for this, this will be included in the next Atom release, 0.202.0

**Pull request merged**
